spring.application.name=Kousay_Najar_TP_4DS9
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/NAJAR_Kousay_TP?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update